name: orca-cd-dev

services:
  hub:
    build:
      context: .
      dockerfile: hub.Dockerfile
    container_name: orca-hub-dev
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data/hub:/app/data
    environment:
      - APP_URL=http://localhost:8080
      - APP_SECRET=supersecretkey_minimum_32_characters
      - AIKIDO_TOKEN=

  agent:
    build:
      context: .
      dockerfile: agent.Dockerfile
    container_name: orca-agent-dev
    use_api_socket: true # Allows container to access Docker API on host
    volumes:
      - ./data/agent/deployments:/deployments
    depends_on:
      hub:
        condition: service_healthy
    environment:
      - HUB_URL=ws://hub:8080/api/v1/ws
      - AUTH_TOKEN=

  pocket-id:
    container_name: pocket-id-dev
    image: ghcr.io/pocket-id/pocket-id:v2
    ports:
      - 127.0.0.1:1411:1411
    volumes:
      - "./data/pocket-id:/app/data"
    environment:
      - APP_URL=http://localhost:1411
      - ENCRYPTION_KEY=supersecretkey_minimum_32_characters
    profiles:
      - pocket-id
